import type { DefaultValues } from "react-hook-form";
import type { CheckoutFormData } from "./schema";

export const CHECKOUT_FORM_DEFAULTS: DefaultValues<CheckoutFormData> = {
  billing_first_name: "",
  billing_last_name: "",
  billing_email: "",
  billing_phone: "",
  billing_company: "",
  billing_address_1: "",
  billing_address_2: "",
  billing_city: "",
  billing_postcode: "",
  billing_country: "AU",
  billing_state: "",
  shipping_first_name: "",
  shipping_last_name: "",
  shipping_company: "",
  shipping_address_1: "",
  shipping_address_2: "",
  shipping_city: "",
  shipping_postcode: "",
  shipping_country: "AU",
  shipping_state: "",
  shipToDifferentAddress: false,
  deliveryAuthority: "with_signature",
  deliveryInstructions: "",
  doNotSendPaperwork: false,
  discreetPackaging: false,
  ndis_number: "",
  ndis_participant_name: "",
  ndis_dob: "",
  ndis_funding_type: "",
  ndis_approval: false,
  billing_ndis_invoice_email: "",
  hcp_number: "",
  hcp_participant_name: "",
  hcp_provider_email: "",
  hcp_approval: false,
  cust_woo_ndis_participant_name: "",
  cust_woo_ndis_number: "",
  cust_woo_ndis_dob: "",
  cust_woo_ndis_funding_type: "",
  cust_woo_invoice_email: "",
  cust_woo_ndis_approval: false,
  cust_woo_hcp_participant_name: "",
  cust_woo_hcp_number: "",
  cust_woo_provider_email: "",
  cust_woo_hcp_approval: false,
  subscribe_newsletter: false,
  insurance_option: "no",
  termsAccepted: false,
};
